# Generated by Django 4.2.4 on 2023-08-20 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("volunteer_listing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Jobapplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Waiting", "Waiting"),
                        ],
                        default="Waiting",
                        max_length=20,
                    ),
                ),
                ("date_applied", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=50)),
                ("last_name", models.CharField(blank=True, max_length=50)),
                (
                    "biography",
                    models.TextField(default="no biography added...", max_length=400),
                ),
                ("email", models.EmailField(blank=True, max_length=150)),
                (
                    "avatar",
                    models.ImageField(default="avatar.png", upload_to="avatars/"),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Organizer", "Organizer"),
                            ("Volunteer", "Volunteer"),
                        ],
                        default="Volunteer",
                        max_length=200,
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "applied_job",
                    models.ManyToManyField(
                        blank=True,
                        related_name="applied_job",
                        through="profiles.Jobapplication",
                        to="volunteer_listing.job",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profiles.profile"
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="volunteer_listing.job"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="jobapplication", unique_together={("job", "applicant")},
        ),
    ]
