# Generated by Django 4.2.4 on 2023-08-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer_listing", "0003_job_description"),
        ("profiles", "0002_profile_applied_job"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="applied_job",),
        migrations.AddField(
            model_name="profile",
            name="applied_job",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="applied_jobs",
                to="volunteer_listing.job",
            ),
        ),
    ]
