# Generated by Django 4.2.4 on 2023-08-15 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=500)),
                ("website", models.CharField(blank=True, max_length=200)),
                ("location", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=250)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("On-site", "On-site"),
                            ("Remote", "Remote"),
                            ("Hybrid", "Hybrid"),
                        ],
                        default="On-site",
                        max_length=100,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("Full Time", "Full Time"),
                            ("Part Time", "Part Time"),
                        ],
                        default="Full Time",
                        max_length=20,
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="volunteer_listing.organization",
                    ),
                ),
                (
                    "tag",
                    models.ManyToManyField(
                        blank=True, related_name="tags", to="volunteer_listing.tag"
                    ),
                ),
            ],
        ),
    ]
