# Generated by Django 4.2.4 on 2023-08-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer_listing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="jobs/"),
        ),
    ]
