# Generated by Django 4.2.4 on 2023-08-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer_listing", "0002_job_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
