# Generated by Django 4.2.4 on 2023-08-20 14:40

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0003_donation_amount_currency_donation_updated_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donation", options={"ordering": ("-created",)},
        ),
        migrations.RenameField(
            model_name="donation", old_name="updated", new_name="created",
        ),
        migrations.AlterField(
            model_name="donation",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[
                    ("GBP", "British Pound"),
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                ],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
    ]
